import '@/styles/globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {cn} from "../lib/utils";
import Footer from "./(footer)/Footer";
import ReactQueryProvider from "../components/react-query/ReactQueryProvider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
    <body className={cn(inter.className, 'pb-mobile-navbar-height',)}>
    <ReactQueryProvider>
      {children}
      <Footer/>
    </ReactQueryProvider>
    </body>
    </html>
  )
}
